version: '3.4'

services: 

  database-clients:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123
    hostname: database-clients
    ports:
      - "3306:3306"
    networks:
      - my-stack

  omnidb:
    image: taivokasper/omnidb
    ports:
      - "8081:8080"
      - "25482:25482"
    stdin_open: true
    tty: true
    networks:
      - my-stack
  
  database-processed-clients:
    image: dwmkerr/dynamodb
    ports:
      - "8010:8000"
    command: -sharedDb
    networks:
      - my-stack
  
  queue-clients-to-process:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8072:15672"
    hostname: my-rabbit
    networks:
      - my-stack

  localstack:
    image: localstack/localstack
    container_name: localstack-aws
    ports:
      - "4567-4593:4567-4593"
      - "8080:8080"
    environment:
      - SERVICES=s3:4572,cloudformation:4581
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack-data:/tmp/localstack

  elastic:
    image: elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
    environment: 
      - iscovery.type=single-node

volumes:
  localstack-data:
    name: localstack-data

networks:
  my-stack:

# docker-compose -f docker-compose.infra.yml up --build